workspace: true

stages:
  - lint

jobs:
- name: linting
  stage: lint
  image: node:12-alpine
  before_script:
  - echo "Start linting"
  script:
  - yarn
  - yarn lint
  after_script:
  - echo "End linting"
  only:
    branches:
    - master
    events:
    - pull_request
