workspace: true

stages:
  - lint
  - test

jobs:
- name: linting
  stage: lint
  image: node:12-alpine
  before_script:
  - echo "Start linting"
  script:
  - yarn
  - yarn lint
  after_script:
  - echo "End linting"
  cache:
    - key: node_modules_$CI_BRANCH
      paths:
      - node_modules
  only:
    branches:
    - master
    events:
    - pull_request

- name: test
  stage: test
  image: node:12-alpine
  script:
  - yarn test
  