workspace: true

stages:
  - install
  - lint
  - test

jobs:
- name: install
  stage: install
  image: node:12-alpine
  script:
  - yarn
  cache:
  - key: node_modules_$CI_BRANCH
    paths:
    - node_modules
    only:
      branches:
      - master
      events:
      - pull_request

- name: show
  state: show
  image: node:12-alpine
  script:
    - echo $CI_BRANCH             # e.g: master
    - echo $YOUR_SECRET           # your secret value
    - echo ${CI_COMMIT_HASH:0:7}  # the commit sha truncated to 7 characters
    - echo ${NAME:-default-name}  # default value
    - echo $PWD           # print current working directory
    - echo $NODE_VERSION  # NodeJS version

- name: linting
  stage: lint
  image: node:12-alpine
  before_script:
  - echo "Start linting"
  script:
  - yarn lint
  after_script:
  - echo "End linting"
  only:
    branches:
    - master
    events:
    - pull_request

- name: unit test
  stage: test
  image: node:12-alpine
  script:
  - yarn test
  only:
    branches:
    - master
    events:
    - pull_request

