workspace: true

stages:
  - install
  - show
  - lint
  - test

default:
  environment:
    ABC_ENV: abc
    TEST_ENV: "dai test"

jobs:
- name: install
  stage: install
  image: node:12-alpine
  script:
  - yarn
  cache:
  - key: node_modules_$CI_BRANCH
    paths:
    - node_modules
    only:
      branches:
      - master
      events:
      - pull_request

- name: show
  stage: show
  image: node:12-alpine
  script:
  - node -v
  - yarn -v
  - echo $CI_BRANCH             # e.g: master
  - echo $MY_SECRET             # my secret value
  - echo ${CI_COMMIT_HASH:0:7}  # the commit sha truncated to 7 characters
  - echo ${NAME:-default-name}  # default value
  - echo $PWD           # print current working directory
  - echo $NODE_VERSION  # NodeJS version
  - export APP_NAME="my app"
  - echo $APP_NAME  # my app
  - echo $ABC_ENV
  - echo $CI_GIT_PROVIDER
  - echo $CI_REPOSITORY
  - echo $CI_BUILD_NUMBER
  - echo $CI_BUILD_TRIGGER
  - echo $CI_WEBHOOK_EVENT
  - echo $CI_WEBHOOK_ACTION
  - echo $CI_COMMIT_SHA
  - echo $CI_COMMIT_MESSAGE

- name: linting
  stage: lint
  image: node:12-alpine
  before_script:
  - echo "Start linting"
  script:
  - yarn lint
  after_script:
  - echo "End linting"
  only:
    branches:
    - master
    events:
    - pull_request

- name: unit test
  stage: test
  image: node:12-alpine
  script:
  - yarn test
  only:
    branches:
    - master
    events:
    - pull_request

